export const browserCoreExamples = [
  "sunclaw browser status",
  "sunclaw browser start",
  "sunclaw browser start --headless",
  "sunclaw browser stop",
  "sunclaw browser tabs",
  "sunclaw browser open https://example.com",
  "sunclaw browser focus abcd1234",
  "sunclaw browser close abcd1234",
  "sunclaw browser screenshot",
  "sunclaw browser screenshot --full-page",
  "sunclaw browser screenshot --ref 12",
  "sunclaw browser snapshot",
  "sunclaw browser snapshot --format aria --limit 200",
  "sunclaw browser snapshot --efficient",
  "sunclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "sunclaw browser navigate https://example.com",
  "sunclaw browser resize 1280 720",
  "sunclaw browser click 12 --double",
  "sunclaw browser click-coords 120 340",
  'sunclaw browser type 23 "hello" --submit',
  "sunclaw browser press Enter",
  "sunclaw browser hover 44",
  "sunclaw browser drag 10 11",
  "sunclaw browser select 9 OptionA OptionB",
  "sunclaw browser upload /tmp/sunclaw/uploads/file.pdf",
  "sunclaw browser upload media://inbound/file.pdf",
  'sunclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "sunclaw browser dialog --accept",
  'sunclaw browser wait --text "Done"',
  "sunclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "sunclaw browser console --level error",
  "sunclaw browser pdf",
];
